website/__init__.py
from flask import Flask, render_template
from datetime import timedelta

def page_not_found(e):
    return render_template("404.html"),404

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "asdfalqwefajsdfpojasdf"
    app.register_error_handler(404, page_not_found)

    from .views import views
    app.register_blueprint(views,url_prefix="/")

    return app


website/views.py
from flask import Blueprint, render_template, request, redirect, session, flash
import requests
import json
from urllib.parse import unquote

views = Blueprint("views",__name__)

with open('website/json/allpoems.json') as file:
  all_poems = file.read()

all_poems = json.loads(all_poems)

with open('website/json/inspector_characters.json') as file:
  inspector_characters = file.read()

inspector_characters = json.loads(inspector_characters)

with open("website/json/rj_characters.json") as file:
    rj_characters = file.read()

rj_characters = json.loads(rj_characters)

with open("website/json/inspector.json") as file:
    inspector_quotes = file.read()

inspector_quotes = json.loads(inspector_quotes)

with open("website/json/rj.json") as file:
    rj_quotes = file.read()

rj_quotes = json.loads(rj_quotes)

with open("website/json/examples.json") as file:
    all_examples = file.read()

all_examples = json.loads(all_examples)

all_poem_names = []
for poem in all_poems:
    all_poem_names.append(poem["name"])

with open("website/json/poetry.json") as file:
    poetry_quotes = file.read()


def get_themes(quotes_list):
    themes = []

    for quote in quotes_list:
        for theme in quote["themes"]:
            if theme not in themes:
                themes.append(theme)
    
    return themes

poetry_quotes = json.loads(poetry_quotes)


@views.route("/",methods=["POST","GET"])
def home():
    try:
        response = requests.get("https://zenquotes.io/api/random")
        quotes_data = response.json()
        quote = quotes_data[0]["q"]
        quote_author = quotes_data[0]["a"]
    except:
        quote = "Revise and you shall pass"
        quote_author = "A Wise Individual"

    return render_template("home.html",quote=quote,quote_author=quote_author)

@views.route("/bypoem/<name>")
def bypoem(name):
    name=unquote(name)
    if name == "all":
        return render_template("bypoem.html",poems=all_poems)
    elif name in all_poem_names:
        quotes = []

        for quote in poetry_quotes:
            if quote["poem"] == name:
                quotes.append({"quote":quote["quote"],"speaker":quote["poem"]})
        url_quotes=quotes
        for quote in quotes:
            quote["quote"] = quote["quote"].replace("&","/")
        return render_template("quotes.html",quotes=quotes,name=name,url_quotes=url_quotes)
    else:
        return render_template("404.html")

@views.route("/bytheme/<text>/<theme>")
def bytheme(text,theme):
    theme=unquote(theme)
    text=unquote(text)
    if theme == "all":
        if text == "poetry":
            themes = get_themes(poetry_quotes)
        elif text == "inspector":
            themes = get_themes(inspector_quotes)
        elif text == "rj":
            themes = get_themes(rj_quotes)

        return render_template("bytheme.html",themes=themes,text=text)
    
    else:
        if text == "poetry":
            all_quotes = poetry_quotes
        elif text == "inspector":
            all_quotes = inspector_quotes
        elif text == "rj":
            all_quotes = rj_quotes
        else:
            return render_template("404.html")

        quotes = []    
        for quote in all_quotes:
            if theme in quote["themes"]:
                if all_quotes == poetry_quotes:
                    quotes.append({"quote":quote["quote"],"speaker":quote["poem"]})
                else:
                    quotes.append({"quote":quote["quote"],"speaker":quote["character"]})
        url_quotes = quotes
        for quote in quotes:
            quote["quote"] = quote["quote"].replace("&","/")
        return render_template("quotes.html",quotes=quotes,name=theme,url_quotes=url_quotes)

@views.route("bycharacter/<text>")
def bycharacter(text):
    text = unquote(text)
    if text == "inspector":
        return render_template("bycharacter.html",characters=inspector_characters)
    elif text == "rj":
        return render_template("bycharacter.html",characters=rj_characters)
    elif text in inspector_characters:
        quotes = []
        for quote in inspector_quotes:
            if text == quote["character"]:
                quotes.append({"quote":quote["quote"],"speaker":quote["character"]})
        url_quotes = quotes
        for quote in quotes:
            quote["quote"] = quote["quote"].replace("&","/")
        return render_template("quotes.html",quotes=quotes,name=text,url_quotes=url_quotes)
    elif text in rj_characters:
        quotes = []
        for quote in rj_quotes:
            if text == quote["character"]:
                quotes.append({"quote":quote["quote"],"speaker":quote["character"]})
        url_quotes = quotes
        for quote in quotes:
            quote["quote"] = quote["quote"].replace("&","/")
        return render_template("quotes.html",quotes=quotes,name=text,url_quotes=url_quotes)
    else:
        return render_template("404.html")

@views.route("/printquotes/<name>/<quotes>")
def printquotes(name,quotes):
    quotes_list = eval(unquote(quotes))
    url_quotes = quotes_list
    name = unquote(name)
    for quote in quotes_list:
        quote["quote"] = quote["quote"].replace("&","/")
    return render_template("pdf_template.html",quotes=quotes_list,name=name,url_quotes=url_quotes)

@views.route("/examples/<id>")
def examples(id):
    if id == "all":
        return render_template("examples.html", examples=all_examples)
    else:
        for example in all_examples:
            if example["id"] == id:
                return render_template("essay.html",essay=example)
            
        return render_template("404.html")

@views.route("/printessay/<id>")
def printessay(id):
    for example in all_examples:
        if example["id"] == id:
                return render_template("printessay.html",essay=example)
        
    return render_template("404.html")
                

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Pass English DB - {% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" , initial-scale=1>
    <link rel="shortcut icon" href="{{ url_for('static', filename='icon.png') }}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    
    <script defer src="/_vercel/insights/script.js"></script>
    <script>
      window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
    </script>

    <script>
  window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
</script>
<script defer src="/_vercel/insights/script.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
    {% block stylesheet %}{% endblock %}
</head>

<body>
    <style>
        @font-face {
            font-family: "JosefinSans"; /*a name to be used later*/
            src: url("{{ url_for('static',filename='JosefinSans.ttf') }} "); /*URL to font*/
        }

        body {
            font-family: 'JosefinSans';
        }
    </style>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#FF8FAB">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="nav-item nav-link fw-bold fs-5" href="/" style="color:white">
                    Pass English DB
                </a>

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fs-5 text-dark" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Power and Conflict
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('views.bypoem', name='all') }}">By Poem</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('views.bytheme', theme='all', text='poetry') }}">By Theme</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fs-5 text-dark" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            An Inspector Calls
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('views.bycharacter', text='inspector') }}">By Character</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('views.bytheme', theme='all', text='inspector') }}">By Theme</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle fs-5 text-dark" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Romeo and Juliet
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ url_for('views.bycharacter', text='rj') }}">By Character</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{{ url_for('views.bytheme', theme='all', text='rj') }}">By Theme</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link fs-5 text-dark" href="{{ url_for('views.examples', id='all') }}" aria-expanded="false">
                            Example Essays
                        </a>
                    </li>

                </ul>
            </div>
    </nav>



    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for message in messages %}
    {% if message[0] == "success" %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Success!</strong> {{message[1]}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% elif message[0] == "error" %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Error!</strong> {{message[1]}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
        {% block content%}{% endblock %}
    </div>


</body>

<footer class="text-center">
    <br>
    <p class="fw-bold">Developed by Krishnanshu Adlakha</p>
    {% block footer %}{% endblock %}
</footer>

</html>

website/templates/bycharacter.html
{% extends "base.html" %}
{% block title %}By Character{% endblock %}
{% block content %}

<br>

<div class="row row-cols-1 g-3">
    {%for character in characters%}
    <div class="container p-3">
        <div class="card">

            <div class="card-body text-center">
                <h4 class="card-title">{{character}}</h4>
            </div>
            <a class="btn btn-light" href="{{ url_for('views.bycharacter', text=character) }}">View Quotes</a>

        </div>
    </div>
        {%endfor%}
        
    </div>
    <br>
    <br>
    <br>

    {% endblock %}

website/templates/bypoem.html
{% extends "base.html" %}
{% block title %}Power and Conflict{% endblock %}
{% block content %}

<br>

<div class="row row-cols-1 g-3">
    {%for poem in poems%}
    <div class="container p-3">
        <div class="card">

            <div class="card-body text-center">
                <h4 class="card-title">{{poem["name"]}}</h4>
                <p class="card-text">
                    {{poem["author"]}}
                </p>
            </div>
            <a class="btn btn-light" href="{{ url_for('views.bypoem', name=poem['name']) }}">View Quotes</a>

        </div>
    </div>
        {%endfor%}
        
    </div>
    <br>
    <br>
    <br>

    {% endblock %}

website/templates/bytheme.html
{% extends "base.html" %}
{% block title %}By Theme{% endblock %}
{% block content %}

<br>

<div class="row row-cols-1 g-3">
    {%for theme in themes%}
    <div class="container p-3">
        <div class="card">

            <div class="card-body text-center">
                <h4 class="card-title">{{theme}}</h4>
            </div>
            <a class="btn btn-light" href="{{ url_for('views.bytheme', theme=theme, text=text) }}">View Quotes</a>

        </div>
    </div>
        {%endfor%}
        
    </div>
    <br>
    <br>
    <br>

    {% endblock %}

website/templates/essay.html
{% extends "base.html" %}
{% block title %}{{essay["shortName"]}}{% endblock %}
{% block content %}
<br>

<div class="align-items-center">
    <h1 align="center" class="fw-bold">{{essay["title"]}}</h1>
    <h4 align="center" class="fst-italic"">Written by {{essay["author"]}}</h4>
    <h5 align="center" class="fw-bold">{{essay["level"]}}</h5>
    <div class="text-center">
        <a class="btn btn-primary text-center" href="{{ url_for('views.printessay', id=essay['id']) }}">Print</a>
    </div>
    <br>
    <p align="center" style="white-space: pre-line;" class="fs-5">{{essay["essay"]}}</p>
</div>
<br>
{% endblock %}

website/templates/examples.html
{% extends "base.html" %}
{% block title %}Example Essays{% endblock %}
{% block content %}

<br>

<div class="row row-cols-1 g-3">
    {%for example in examples%}
    <div class="container p-3">
        <div class="card">

            <div class="card-body text-center">
                <h4 class="card-title fw-bold">{{example["title"]}}</h4>
                <p class="card-text fs-5">
                    {{example["author"]}}
                </p>
                <p class="card-text">
                    {{example["level"]}}
                </p>
            </div>
            <a class="btn btn-light" href="{{ url_for('views.examples', id=example['id']) }}">View Essay</a>

        </div>
    </div>
        {%endfor%}
        
    </div>
    <br>
    <br>
    <br>

    {% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<br>

<div class="align-items-center">
    <div class="text-center">
        <img src="{{ url_for('static',filename='aqa_logo.png') }}" width="200" alt="AQA Logo">
    </div>
    <br>
    <h1 align="center" class="fw-bold">All your essential GCSE English Literature quotes in one place to help you pass your exams.</h1>
    <br>
    <h4 align="center" class="fst-italic"">"{{quote}}" - <h3 class="fw-bold" align="center">{{quote_author}}</h3></h4>
</div>
<br>
{% endblock %}

website/templates/pdf_template.html
<!DOCTYPE html>
<html>

<head>
    <title>Pass English DB - Print</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" , initial-scale=1>
    <link rel="shortcut icon" href="{{ url_for('static', filename='icon.png') }}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
</head>

<body onload = "printWindow()">
    <style>
        @font-face {
            font-family: "JosefinSans"; /*a name to be used later*/
            src: url("{{ url_for('static',filename='JosefinSans.ttf') }} "); /*URL to font*/
        }

        body {
            font-family: "JosefinSans";
        }
    </style>
    
    <h1 class="text-center fw-bold">{{name}}</h2>
    <p class="fw-bold text-center">Explore more at passenglish.vercel.app - Developed by Krishnanshu Adlakha</p>
        <br>
        <div class="row row-cols-1 g-3">
            {%for quote in quotes%}
            <div class="container p-3">
                <div class="card">

                <div class="card-body text-center">
                    <p class="card-text fs-4 fst-italic">
                        "{{quote["quote"]}}"
                    </p>
                    <p class="card-text fs-5 fw-bold">{{quote["speaker"]}}</p>
                </div>
                </div>
            </div>
            {%endfor%}

        </div>
        <br>
        <br>
        <br>

        <script type="text/javascript">
            function printWindow() {
                window.print()
            }

            function goBack() {
                history.back()
            }
            
         </script>
</body>


</html>

website/templates/printessay.html
<!DOCTYPE html>
<html>

<head>
    <title>Pass English DB - Print</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" , initial-scale=1>
    <link rel="shortcut icon" href="{{ url_for('static', filename='icon.png') }}" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />
</head>

<body onload="printWindow()">

    <style>
        @font-face {
            font-family: "JosefinSans";
            /*a name to be used later*/
            src: url("{{ url_for('static',filename='JosefinSans.ttf') }} ");
            /*URL to font*/
        }

        body {
            font-family: "JosefinSans";
        }
    </style>

    <div class="align-items-center">
        <h1 align="center" class="fw-bold">{{essay["title"]}}</h1>
        <h4 align="center" class="fst-italic"">Written by {{essay["author"]}}</h4>
            <h5 align="center" class="fw-bold">{{essay["level"]}}</h5>
            <br>
            <p align="center" style="white-space: pre-line;" class="fs-6">{{essay["essay"]}}</p>
    </div>
    <br>
    <script type="text/javascript">
        function printWindow() {
            window.print()
        }

        function goBack() {
            history.back()
        }

    </script>
</body>

<footer class="text-center">
    <br>
    <p class="fw-bold">Explore more at passenglish.vercel.app - Developed by Krishnanshu Adlakha</p>
</footer>

</html>

website/templates/quotes.html
{% extends "base.html" %}
{% block title %}{{name}}{% endblock %}
{% block content %}

<br>
<h1 class="text-center fw-bold">{{name}}</h2>
    <div class="text-center">
        <a class="btn btn-primary text-center" href="{{ url_for('views.printquotes', name=name, quotes=url_quotes) }}">Print</a>
    </div>
    <br>
    <div class="row row-cols-1 g-3">
        {%for quote in quotes%}
        <div class="container p-3">
            <div class="card">

                <div class="card-body text-center">
                    <p class="card-text fs-4 fst-italic">
                        "{{quote["quote"]}}"
                    </p>
                    <p class="card-text fs-5 fw-bold">{{quote["speaker"]}}</p>
                </div>
            </div>
        </div>
        {%endfor%}

    </div>
    <br>
    <br>
    <br>

    {% endblock %}